debug: true

server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  compression:
    enabled: true
spring:
  application:
    name: CodeSharingCommunityZuulGateway
  cloud:
    config:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      username: root
      password: pyb***20000112
      jdbc-url: jdbc:mysql://localhost:3306/code_sharing_community?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      key-prefix: ${spring.application.name}
      time-to-live: 30s
  redis:
    host: localhost
    password: pyb***20000112
    port: 6379
    jedis:
      pool:
        max-active: 60
        max-wait: 60
        max-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:MM:ss
    time-zone: GMT+8
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
  instance:
    instance-id: CodeSharingCommunity_路由网关
    prefer-ip-address: true
zuul:
  sensitive-headers:
  ignored-services: '*'
  add-proxy-headers: true
  add-host-header: true
  routes:
    CodeSharingCommunityRest:
      path: /**
      service-id: CodeSharingCommunityRest
  ignored-patterns: /login, /logout, /nav, /applyCode, /applyAccount
info:
  app.name: CodeSharingCommunity_路由网关_01
  company.name: www.halfdream.cn/半梦的个人网址
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

hystrix:
  command:
    default:
      executio:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000

mybatis-plus:
  type-enums-package: com.pdsu.banmeng.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
